### ISSUE TITLE
Gzip and base64 

### ISSUE THREAD

**Issue by zygisjas** [ocrdu/arduino-webinterface-websocket-ap#2]
It's not an issue more like a question. There is no mention of the tool you used to compress the webpage?

Could you please provide information regarding that?

**Comment by ocrdu** [comment]
You can use anything that creates a compressed file the browser understands, as long as you send the right Content-Encoding header, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding .

**Comment by zygisjas** [comment]
> You can use anything that creates a compressed file the browser understands, as long as you send the right Content-Encoding header, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding .

I've used this command in my Linux machine:

`cat page.html | gzip | base64 -w0`
